CONTIKI = ../..

ifndef TARGET
TARGET = sky
endif

CONTIKI_PROJECT = rime-mobiwise

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

CONTIKI_WITH_RIME = 1

MODULES += 

APPS +=

all: sensor-node sink-node

include $(CONTIKI)/Makefile.include
